Mpy optimizations
ayoy/micropython-thermal-printer pull request #2
Opened 2017-12-21 06:02 UTC by mgalka

- A few changes in miliseconds operations.
- Make it work on ESP8266
- Some small code improvements.

2017-12-21 14:11 UTC, ayoy requested changes

2017-12-21 14:11 UTC, ayoy commented on Adafruit_Thermal.py
> +		self.resumeTime = utime.ticks_add(utime.ticks_ms(), x)
`ticks_add()` is not implemented in Pycom's micropython. As discussed, we should probably make a hardware-dependent wrapper for it.

2017-12-24 11:39 UTC, mgalka commented
I've added requested changes and tried to resolved conflicts, but for some reason, it still says that those need to be resolved.
Any idea how I may proceed?

2017-12-24 12:10 UTC, ayoy commented
I have recently removed the `*1000` from `timeoutWait()` and you might have missed that changes when you pulled to resolve conflicts. You can try the [web editor](https://github.com/ayoy/micropython-thermal-printer/pull/2/conflicts) to resolve them :)

2017-12-26 19:38 UTC, ayoy approved these changes

2017-12-26 19:39 UTC, merged